# Principle Component Analysis

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
import math

### Loading Data

In [2]:
data = pd.read_csv("../input/home-data-for-ml-course/train.csv")

In [3]:
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

### Input and Output Vectors

In [4]:
endog = data['SalePrice']
exog = sm.add_constant(data[['OverallQual','YearBuilt','YearRemodAdd','TotalBsmtSF','1stFlrSF','GrLivArea','FullBath','TotRmsAbvGrd','GarageCars','GarageArea']])
print(exog)

      const  OverallQual  YearBuilt  YearRemodAdd  TotalBsmtSF  1stFlrSF  \
0       1.0            7       2003          2003          856       856   
1       1.0            6       1976          1976         1262      1262   
2       1.0            7       2001          2002          920       920   
3       1.0            7       1915          1970          756       961   
4       1.0            8       2000          2000         1145      1145   
...     ...          ...        ...           ...          ...       ...   
1455    1.0            6       1999          2000          953       953   
1456    1.0            6       1978          1988         1542      2073   
1457    1.0            7       1941          2006         1152      1188   
1458    1.0            5       1950          1996         1078      1078   
1459    1.0            5       1965          1965         1256      1256   

      GrLivArea  FullBath  TotRmsAbvGrd  GarageCars  GarageArea  
0          1710      

In [5]:
X = exog.to_numpy()
Y = endog.to_numpy()
print(X)

[[1.000e+00 7.000e+00 2.003e+03 ... 8.000e+00 2.000e+00 5.480e+02]
 [1.000e+00 6.000e+00 1.976e+03 ... 6.000e+00 2.000e+00 4.600e+02]
 [1.000e+00 7.000e+00 2.001e+03 ... 6.000e+00 2.000e+00 6.080e+02]
 ...
 [1.000e+00 7.000e+00 1.941e+03 ... 9.000e+00 1.000e+00 2.520e+02]
 [1.000e+00 5.000e+00 1.950e+03 ... 5.000e+00 1.000e+00 2.400e+02]
 [1.000e+00 5.000e+00 1.965e+03 ... 6.000e+00 1.000e+00 2.760e+02]]


In [6]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig

In [7]:
M = mean(X.T, axis=1)
print(M)


[1.00000000e+00 6.09931507e+00 1.97126781e+03 1.98486575e+03
 1.05742945e+03 1.16262671e+03 1.51546370e+03 1.56506849e+00
 6.51780822e+00 1.76712329e+00 4.72980137e+02]


In [8]:
C= X-M
print(C)

[[ 0.00000000e+00  9.00684932e-01  3.17321918e+01 ...  1.48219178e+00
   2.32876712e-01  7.50198630e+01]
 [ 0.00000000e+00 -9.93150685e-02  4.73219178e+00 ... -5.17808219e-01
   2.32876712e-01 -1.29801370e+01]
 [ 0.00000000e+00  9.00684932e-01  2.97321918e+01 ... -5.17808219e-01
   2.32876712e-01  1.35019863e+02]
 ...
 [ 0.00000000e+00  9.00684932e-01 -3.02678082e+01 ...  2.48219178e+00
  -7.67123288e-01 -2.20980137e+02]
 [ 0.00000000e+00 -1.09931507e+00 -2.12678082e+01 ... -1.51780822e+00
  -7.67123288e-01 -2.32980137e+02]
 [ 0.00000000e+00 -1.09931507e+00 -6.26780822e+00 ... -5.17808219e-01
  -7.67123288e-01 -1.96980137e+02]]


In [9]:
V = cov(C.T)
print(V)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.91267945e+00 2.39062151e+01 1.57234172e+01
  3.26303447e+02 2.54612835e+02 4.30960770e+02 4.19509985e-01
  9.60875811e-01 6.20813655e-01 1.66184976e+02]
 [0.00000000e+00 2.39062151e+01 9.12215413e+02 3.69675456e+02
  5.18680746e+03 3.29248729e+03 3.15848985e+03 7.79167801e+00
  4.69262302e+00 1.21398594e+01 3.09285728e+03]
 [0.00000000e+00 1.57234172e+01 3.69675456e+02 4.26232822e+02
  2.63625372e+03 1.91852970e+03 3.11780801e+03 4.99366239e+00
  6.43419494e+00 6.48962040e+00 1.64027423e+03]
 [0.00000000e+00 3.26303447e+02 5.18680746e+03 2.63625372e+03
  1.92462362e+05 1.38990726e+05 1.04861241e+05 7.82403715e+01
  2.03632854e+02 1.42479105e+02 4.56479174e+04]
 [0.00000000e+00 2.54612835e+02 3.29248729e+03 1.91852970e+03
  1.38990726e+05 1.49450079e+05 1.14984528e+05 8.10671435e+01
  2.57322279e+02

In [10]:
values, vectors = eig(V)
print(vectors)


[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 1.32309022e-03 -2.86762468e-04 -2.11894520e-03  6.24534722e-04
  -1.66426437e-02  6.03496628e-03 -2.61687225e-01 -9.62467532e-01
  -5.27212265e-02 -4.55676164e-02  0.00000000e+00]
 [ 1.52409619e-02  1.31957536e-02 -6.50544807e-02  1.54671102e-03
  -8.70673043e-01 -4.86925523e-01  4.10417118e-03  1.14142421e-02
  -1.03327713e-03 -6.54971421e-03  0.00000000e+00]
 [ 1.01628827e-02 -6.83758684e-04 -2.89161095e-02  2.10194900e-03
  -4.85892944e-01  8.73368414e-01  4.22133181e-03  1.29112842e-02
   3.78804486e-04 -2.58544498e-03  0.00000000e+00]
 [ 5.37012381e-01  5.85223345e-01 -1.43879630e-01  5.89600870e-01
   2.80517225e-02  3.62141122e-03  5.97797169e-04  6.25062976e-04
   7.28169880e-05  1.95699785e-04  0.00000000e+00]
 [ 4.98556766e-01  3.32960986e-01  4.19608206e-01 -6.81293499e-01
  -1.85990289e-02 -

In [11]:
print(values)

[4.65354269e+05 1.40280365e+05 3.09042816e+04 2.75521556e+04
 7.87776591e+02 2.17828512e+02 8.22738000e-01 7.05952218e-01
 1.03513860e-01 1.40492602e-01 0.00000000e+00]


### Project Data

In [12]:

P = vectors.T.dot(C.T)
print(P.T)

[[-1.19075770e+02 -3.62336034e+02 -1.57959667e+02 ... -1.83191386e-01
  -6.03684431e-02  0.00000000e+00]
 [-8.71428838e+00  3.40037528e+02  9.19768365e+00 ...  1.08069237e-01
   6.44944316e-01  0.00000000e+00]
 [ 8.14865413e+00 -3.58949061e+02 -1.89273322e+02 ... -2.82334236e-01
   5.61826076e-02  0.00000000e+00]
 ...
 [ 5.60348971e+02 -5.49059096e+02  2.42862065e+02 ... -1.93788005e-01
  -1.63967966e-02  0.00000000e+00]
 [-3.61224812e+02  3.03739218e+02  1.45130168e+02 ...  8.13361628e-02
  -1.54220042e-01  0.00000000e+00]
 [-5.38559397e+01  3.36321234e+02  1.72279352e+02 ... -1.64860776e-02
  -3.21645761e-01  0.00000000e+00]]


In [13]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)
principalComponents = pca.fit_transform(X)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1'])

In [14]:
exog1 = sm.add_constant(principalDf[['principal component 1']])
print(exog1)


      const  principal component 1
0       1.0            -119.075770
1       1.0              -8.714288
2       1.0               8.148654
3       1.0             -99.791743
4       1.0             553.406273
...     ...                    ...
1455    1.0             -76.500007
1456    1.0            1083.694697
1457    1.0             560.348971
1458    1.0            -361.224812
1459    1.0             -53.855940

[1460 rows x 2 columns]


In [15]:
from sklearn import linear_model
lm = linear_model.LinearRegression()
model = lm.fit(exog1,endog)
lm.coef_

array([ 0.        , 90.50964636])

In [16]:
lm.intercept_

180921.19589041095

In [17]:
def RSE(y_true, y_predicted):
   
    y_true = np.array(y_true)
    y_predicted = np.array(y_predicted)
    RSS = np.sum(np.square(y_true - y_predicted))

    rse = math.sqrt(RSS / (len(y_true) - 2))
    return rse

In [18]:
ypred =lm.predict(exog1)

In [19]:
re = RSE(endog,ypred)
print(re)

50006.44817013513


### I hope you liked my Notebook